xof 0302txt 0032

// Direct3D .x file translation of Scene_Root
// Generated by 3DSMax Prepar3D v4 Exporter Plug-in, Version 1.00
// Wed May 24 14:33:50 2017


template Header {
 <3D82AB43-62DA-11cf-AB39-0020AF71E433>
 WORD major;
 WORD minor;
 DWORD flags;
}

template GuidToName {
 <7419dfe5-b73a-4d66-98d8-c082591dc9e7>
 STRING Guid;
 STRING Name;
}

template OverrideBoundingBox {
 <03390521-5EF8-49F0-B6D3-6E91B2068A91>
 Boolean OverrideBoundingBox;
 Vector BoundingBoxMin;
 Vector BoundingBoxMax;
}

template OverrideRadius {
 <6400393B-6210-4917-99C8-968D4DEE0F3A>
 Boolean OverrideRadius;
 FLOAT Radius;
}

template Vector {
 <3D82AB5E-62DA-11cf-AB39-0020AF71E433>
 FLOAT x;
 FLOAT y;
 FLOAT z;
}
template SkinWeight {
 <C3B5EDF9-7345-463d-96D7-6386E2EC4030>
 STRING boneRef;
 FLOAT weight;
}


template SkinWeightGroup {
 <E7B502DB-0C05-4288-A025-80762E19E0AB>
 DWORD nWeights;
 array SkinWeight skinWeights[nWeights];
}


template Coords2d {
 <F6F23F44-7686-11cf-8F52-0040333594A3>
 FLOAT u;
 FLOAT v;
}

template Matrix4x4 {
 <F6F23F45-7686-11cf-8F52-0040333594A3>
 array FLOAT matrix[16];
}

template ColorRGBA {
 <35FF44E0-6C7C-11cf-8F52-0040333594A3>
 FLOAT red;
 FLOAT green;
 FLOAT blue;
 FLOAT alpha;
}

template ColorRGB {
 <D3E16E81-7835-11cf-8F52-0040333594A3>
 FLOAT red;
 FLOAT green;
 FLOAT blue;
}

template TextureFilename {
 <A42790E1-7810-11cf-8F52-0040333594A3>
 STRING filename;
}

template Material {
 <3D82AB4D-62DA-11cf-AB39-0020AF71E433>
 ColorRGBA faceColor;
 FLOAT power;
 ColorRGB specularColor;
 ColorRGB emissiveColor;
 [...]
}

template MeshFace {
 <3D82AB5F-62DA-11cf-AB39-0020AF71E433>
 DWORD nFaceVertexIndices;
 array DWORD faceVertexIndices[nFaceVertexIndices];
}

template MeshTextureCoords {
 <F6F23F40-7686-11cf-8F52-0040333594A3>
 DWORD nTextureCoords;
 array Coords2d textureCoords[nTextureCoords];
}

template MeshTextureCoords2 {
 <564556B9-6802-49AB-8910-31D759C378CF>
 DWORD nTextureCoords;
 array Coords2d textureCoords[nTextureCoords];
}

template MeshSkinWeights {
 <C7E2131A-30F3-4eb9-AACC-E0AE11D8FE62>
 DWORD nVertices;
 array SkinWeightGroup skinWeights[nVertices];
}

template MeshMaterialList {
 <F6F23F42-7686-11cf-8F52-0040333594A3>
 DWORD nMaterials;
 DWORD nFaceIndexes;
 array DWORD faceIndexes[nFaceIndexes];
 [Material]
}

template MeshNormals {
 <F6F23F43-7686-11cf-8F52-0040333594A3>
 DWORD nNormals;
 array Vector normals[nNormals];
 DWORD nFaceNormals;
 array MeshFace faceNormals[nFaceNormals];
}

template Mesh {
 <3D82AB44-62DA-11cf-AB39-0020AF71E433>
 DWORD nVertices;
 array Vector vertices[nVertices];
 DWORD nFaces;
 array MeshFace faces[nFaces];
 [...]
}

template BoneInfo {
 <1FF0AE59-4B0B-4dfe-88F2-91D58E395767>
 STRING boneName;
}

template AnimLinkName {
 <0057EC91-F96B-4f5e-9CFB-0E305F39DA1A>
 STRING linkName;
}

template IKChain {
 <2684B333-AAB2-45d9-87D8-6E2BB22616AD>
 STRING chainName;
 STRING startNode;
 STRING endNode;
}

template ConstraintInfo {
 <8713D495-C538-44dc-AE54-1097E7C93D13>
 Boolean bActive;
 Boolean bLimited;
 FLOAT fUpperLimit;
 FLOAT fLowerLimit;
}

// Note that the exported rotation order is YZX
template JointConstraint {
 <BE433CF1-BCC0-43f8-9FE5-DB0556414426>
 array ConstraintInfo Rotation[3];
 array ConstraintInfo Translation[3];
}

template FrameTransformMatrix {
 <F6F23F41-7686-11cf-8F52-0040333594A3>
 Matrix4x4 frameMatrix;
}

template Frame {
 <3D82AB46-62DA-11cf-AB39-0020AF71E433>
 [...]
}
template FloatKeys {
 <10DD46A9-775B-11cf-8F52-0040333594A3>
 DWORD nValues;
 array FLOAT values[nValues];
}

template TimedFloatKeys {
 <F406B180-7B3B-11cf-8F52-0040333594A3>
 DWORD time;
 FloatKeys tfkeys;
}

template AnimationKey {
 <10DD46A8-775B-11cf-8F52-0040333594A3>
 DWORD keyType;
 DWORD nKeys;
 array TimedFloatKeys keys[nKeys];
}

template AnimationOptions {
 <E2BF56C0-840F-11cf-8F52-0040333594A3>
 DWORD openclosed;
 DWORD positionquality;
}

template Animation {
 <3D82AB4F-62DA-11cf-AB39-0020AF71E433>
 [...]
}

template AnimationSet {
 <3D82AB50-62DA-11cf-AB39-0020AF71E433>
 [Animation]
}

template DiffuseTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07401>
 STRING filename;
}

template DiffuseTextureUVChannel {
 <E0A8A960-BA3F-4E17-805C-D0B94831BAA4>
 DWORD uvChannel;
}

template SpecularTextureFileName {
 <DF64E0D7-4FFA-4634-9DA0-3EF2FAA081CE>
 STRING filename;
}

template SpecularTextureUVChannel {
 <0E95C17B-0AEF-4D07-BA90-E4B2CD5E01AE>
 DWORD uvChannel;
}

template AmbientTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07402>
 STRING filename;
}

template AmbientTextureUVChannel {
 <FAADED67-439E-446F-B96B-5381A0DC731F>
 DWORD uvChannel;
}

template EmissiveTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07403>
 STRING filename;
}

template EmissiveTextureUVChannel {
 <F8EF95D3-0307-41C7-9A42-CBE434A97BFA>
 DWORD uvChannel;
}

template ReflectionTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07404>
 STRING filename;
}

template ShininessTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07405>
 STRING filename;
}

template ShininessTextureUVChannel {
 <98C9B8F8-4A0F-48C7-9886-38299FB8210B>
 DWORD uvChannel;
}

template BumpTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07406>
 STRING filename;
}

template BumpTextureUVChannel {
 <12B12581-A164-4D63-AB12-41B2F43F7793>
 DWORD uvChannel;
}

template DisplacementTextureFileName {
 <E00200E2-D4AB-481a-9B85-E20F9AE07407>
 STRING filename;
}

template DisplacementTextureUVChannel {
 <BB58EEEF-9200-42FA-BF5F-4297948CD2BA>
 DWORD uvChannel;
}

template DetailTextureFileName {
 <C223DC28-5C0E-41bc-9706-A30E023EF118>
 STRING filename;
}

template DetailTextureUVChannel {
 <6BCF39C7-4E24-4977-803A-521BABF54D34>
 DWORD uvChannel;
}

template FresnelTextureFileName {
 <C16742E5-974D-4576-870D-2047C79DF7A9>
 STRING filename;
}

template P3DMaterial {
 <16B4B490-C327-42e3-8A71-0FA35C817EA2>
 ColorRGBA FallbackDiffuse;
 ColorRGB  Specular;
 FLOAT     Power;
 FLOAT     DetailScale;
 FLOAT     BumpScale;
 FLOAT     EnvironmentLevelScale;
 Boolean   bUseGlobalEnv;
 Boolean   bModEnvInvDiffuseAlpha;
 Boolean   bModEnvSpecularMapAlpha;
 Boolean   bFresnelDiffuse; Boolean bFresnelSpecular; Boolean bFresnelEnvironment;
 Boolean   bUsePrecipitation;
 Boolean   bPrecipOffset;
 FLOAT     PrecipOffset;
 FLOAT     SpecMapPowerScale;
 STRING    SrcBlend;
 STRING    DstBlend;
 [...]
}

template AllowBloom {
 <D66E37C9-9DFE-4092-8565-C6E4C3498235>
 Boolean     AllowBloom;
}

template BloomData {
 <58ED1E67-0D18-44EF-B676-40BB20C1EE88>
 Boolean BloomCopy;
 Boolean BloomModAlpha;
}

template SpecularBloomFloor {
 <21195174-A31D-47ed-BE5A-04ACAD4C3544>
 FLOAT     SpecularBloomFloor;
}

template AmbientLightScale {
 <4CC76AEB-E84F-4688-AB49-E1DC4B9273C7>
 FLOAT     AmbientLightScale;
}

template EmissiveData {
 <A02EF480-3ED3-433d-A71D-5CAC4775757A>
 STRING   EmissiveBlend;
}

template AlphaData {
 <10DB69F3-E0EE-4fb3-8055-63E539EF5885>
 Boolean  ZTestAlpha;
 FLOAT    AlphaTestValue;
 STRING   AlphaTestFunction;
 Boolean  FinalAlphaWrite;
 FLOAT    FinalAlphaWriteValue;
}

template MaskDiffuseBlendsByDetailBlendMask {
 <442265E0-6F93-43C8-8310-C3E1E6848833>
 Boolean  MaskDiffuseBlendsByDetailBlendMask;
}

template MaskFinalAlphaBlendByDetailBlendMask {
 <73671D1D-535E-4DC6-A543-5B226273C5DA>
 Boolean  MaskFinalAlphaBlendByDetailBlendMask;
}

template EnhancedParameters {
 <99CAD20D-DCC5-4ad4-ADAE-ED3CDE30CC02>
 Boolean  AssumeVerticalNormal;
 Boolean  ZWriteAlpha;
 Boolean  NoZWrite;
 Boolean  VolumeShadowDeprecated;
 Boolean  NoShadow;
 Boolean  PrelitVertices;
}

template BaseMaterialSpecular {
 <E294ED4E-5C5A-4927-B19A-6A2D445FAF24>
 Boolean  AllowBaseMaterialSpecular;
}

template BaseMaterialSkin {
 <B640F860-9E28-4cab-AD46-CACCE2A418AC>
 Boolean  AllowSkinning;
}

template DoubleSidedMaterial {
 <B1C6C3B0-DD1A-417b-919A-B04BAD6AE06D>
 Boolean  DoubleSided;
}

template BlendConstantSetting {
 <48EA96C3-588E-451d-B4BB-0C746C8380D9>
 Boolean  BlendConstant;
}

template ForceTextureAddressWrapSetting {
 <046EE84C-7977-4a11-AA2B-C79FF5391EDD>
 Boolean  ForceTextureAddressWrap;
}

template ForceTextureAddressClampSetting {
 <DB108D57-A3A8-4b76-8CB0-8379CDDEC074>
 Boolean  ForceTextureAddressClamp;
}

template ZBiasValue {
 <66F4E05E-94B9-4F07-AE1B-1FFE66810F4E>
 FLOAT  ZBias;
}

template NoSpecularBloom {
 <BCE314D2-15DB-4ffd-9F6F-0763B2A4616F>
 Boolean  AllowSpecularBloom;
}

template EmissiveBloom {
 <5FF8D7A2-30B5-41bc-A891-28A427D78246>
 Boolean  AllowEmissiveBloom;
}

template BlendDiffuseByBaseAlpha {
 <A623FA7C-37CB-4d17-B702-854E0DBDB467>
 Boolean  BlendDiffByBaseAlpha;
}

template BlendDiffuseByInverseSpecularMapAlpha {
 <DAA68529-1C27-4182-9D97-E631A4759EA7>
 Boolean  BlendDiffuseByInvSpecAlpha;
}

template NNumberTexture {
 <E49E744A-CDBE-40c1-9C89-4A46BEB44D33>
 Boolean  IsNNumberTexture;
}

template MaterialScript {
 <2EE1D70C-4903-4205-AB03-B4A21BF7F323>
 STRING  MaterialScriptFilename;
}

template UseEmissiveAlphaAsHeatMap {
 <F5A3E710-014D-450F-8597-78D00D4AC048>
 Boolean  UseEmissiveAlphaHeatMap;
}

template TemperatureScale {
 <8215033A-0F10-45F0-8493-5C60DC4DD5B5>
 FLOAT  TemperatureScalar;
}

template DetailColor {
 <68E59B99-A9A1-4E27-8660-6B83520657BB>
 ColorRGBA  DetailColor;
}

template DetailTextureParameters {
 <B1D63F06-FCFB-4DCA-B51A-8889A594EBAE>
 FLOAT    DetailOffsetU;
 FLOAT    DetailOffsetV;
 FLOAT    DetailRotation;
 FLOAT    DetailScaleV;
 STRING   DetailBlendMode;
 FLOAT    DetailBlendWeight;
 Boolean  UseDetailAlphaAsBlendMask;
}

template PartData {
 <79B183BA-7E70-44d1-914A-23B304CA91E5>
 DWORD nByteCount;
 array BYTE XMLData[ nByteCount ];
}

Header {
	1;
	0;
	1;
}

GuidToName {
	"{34f29418-f178-430f-8ac7-530b22af48c0}";
	"SceneryObjectSample";
}

OverrideBoundingBox {
	0;
	0.000000; 0.000000; 0.000000;
	0.000000; 0.000000; 0.000000;
}

OverrideRadius {
	0;
	0.000000;
}

//=====================
// FILE NODE HEIRARCHY
//=====================
// Scene_Root (5 Children)
//   Building (0 Children)
//   Chimney (0 Children)
//   Barrel2 (0 Children)
//   Barrel0 (0 Children)
//   Barrel1 (0 Children)

Frame frm-MasterScale {
FrameTransformMatrix {
   0.000977, 0.0, 0.0, 0.0,
   0.0, 0.000977, 0.0, 0.0,
   0.0, 0.0, 0.000977, 0.0,
   0.0, 0.0, 0.0, 1.0;;
}		// End frm-MasterScale FrameTransformMatrix
Frame frm-MasterUnitConversion {
FrameTransformMatrix {
   1024.000000, 0.0, 0.0, 0.0,
   0.0, 1024.000000, 0.0, 0.0,
   0.0, 0.0, 1024.000000, 0.0,
   0.0, 0.0, 0.0, 1.0;;
}		// End frm-MasterUnitConversion FrameTransformMatrix
Frame RotateAroundX {
FrameTransformMatrix {
   1.0, 0.0, 0.0, 0.0,
   0.0, 0.0, 1.0, 0.0,
   0.0, -1.0, 0.0, 0.0,
   0.0, 0.0, 0.0, 1.0;;
}		// End Frame RotateAroundX FrameTransformMatrix
Frame frm-Building {
FrameTransformMatrix {
  1.000000, 0.000000, -0.000000, 0.0,
  0.000000, 1.000000, -0.000000, 0.0,
  -0.000000, -0.000000, 1.000000, 0.0,
  0.000000, 0.000000, -0.000000, 1.0;;
}		// End FrameTransformMatrix

Mesh Building {
41;		// Mesh 'Building' contains 41 vertices
  -10.000000; -5.000000; -0.000000;,
  10.000000; -5.000000; -0.000000;,
  -10.000000; 5.000000; -0.000000;,
  10.000000; 5.000000; -0.000000;,
  -10.000000; -5.000000; -3.500000;,
  10.000000; -5.000000; -3.500000;,
  -10.000000; 5.000000; -3.500000;,
  10.000000; 5.000000; -3.500000;,
  -4.998793; -2.499397; -7.000000;,
  4.998793; -2.499397; -7.000000;,
  -4.998793; 2.499397; -7.000000;,
  4.998793; 2.499397; -7.000000;,
  -10.000000; -5.000000; -0.000000;,
  10.000000; -5.000000; -0.000000;,
  -10.000000; -5.000000; -0.000000;,
  10.000000; -5.000000; -0.000000;,
  10.000000; 5.000000; -0.000000;,
  10.000000; -5.000000; -3.500000;,
  10.000000; -5.000000; -0.000000;,
  10.000000; 5.000000; -0.000000;,
  -10.000000; 5.000000; -0.000000;,
  10.000000; 5.000000; -3.500000;,
  10.000000; 5.000000; -0.000000;,
  -10.000000; 5.000000; -0.000000;,
  -10.000000; -5.000000; -0.000000;,
  -10.000000; -5.000000; -3.500000;,
  -10.000000; -5.000000; -3.500000;,
  -10.000000; 5.000000; -3.500000;,
  -10.000000; 5.000000; -0.000000;,
  -10.000000; -5.000000; -3.500000;,
  10.000000; -5.000000; -3.500000;,
  -10.000000; -5.000000; -3.500000;,
  10.000000; -5.000000; -3.500000;,
  10.000000; 5.000000; -3.500000;,
  10.000000; -5.000000; -3.500000;,
  10.000000; 5.000000; -3.500000;,
  -10.000000; 5.000000; -3.500000;,
  10.000000; 5.000000; -3.500000;,
  -10.000000; 5.000000; -3.500000;,
  -10.000000; -5.000000; -3.500000;,
  -10.000000; 5.000000; -3.500000;;

20;		// Mesh 'Building' contains 20 Faces
  3; 3, 2, 0;,
  3; 0, 1, 3;,
  3; 11, 9, 8;,
  3; 8, 10, 11;,
  3; 5, 13, 12;,
  3; 14, 4, 5;,
  3; 7, 16, 15;,
  3; 18, 17, 7;,
  3; 6, 20, 19;,
  3; 22, 21, 6;,
  3; 25, 24, 23;,
  3; 28, 27, 26;,
  3; 9, 30, 29;,
  3; 31, 8, 9;,
  3; 11, 33, 32;,
  3; 34, 9, 11;,
  3; 10, 36, 35;,
  3; 37, 11, 10;,
  3; 8, 39, 38;,
  3; 40, 10, 8;;
MeshMaterialList {
  1; // 1 Materials
  20; // 20 Faces have materials specified
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0;
  Material House0 {
  0.588000; 0.588000; 0.588000; 1.000000;;
  0.000000;
  0.900000; 0.900000; 0.900000;;
  0.000000; 0.000000; 0.000000;;
  TextureFileName {
     "IRSceneryObject_t.dds";
  }
  DiffuseTextureFileName  {
    "IRSceneryObject_t.dds";
  }
  EmissiveTextureFileName  {
    "IRSceneryObject_t_lm.dds";
  }
  P3DMaterial {
    0.588000; 0.588000; 0.588000; 1.000000;; // Diffuse component
    0.900000; 0.900000; 0.900000;;     // Specular component
    0.000000;              // Specular power
    1.000000; 1.000000;          // Detail scale U and bump scale
    1.000000;              // Scale environment level factor
    0;              // Do not use global environment
    0;              // Do not blend env by inv diffuse alpha
    0;              // Do not blend env by specular map alpha
    0; 0; 0;      // Fresnel - diffuse = NO, Specular = NO, Env = NO
    0; 0; 0.000000;      // Precipitation - Use = NO, Offset = NO
    64.000000;              // Specular Map Power Scale
    "One"; "Zero";  // Src/Dest blend
    BlendDiffuseByBaseAlpha  {
      0;
    }
    BlendDiffuseByInverseSpecularMapAlpha  {
      0;
    }
    AllowBloom  {
      1;
    }
    SpecularBloomFloor  {
      0.900000;
    }
    EmissiveData  {
      "AdditiveNightOnly";  // Emissive mode
    }
    AlphaData  {
      0;  // ZTest Alpha
      0.000000;  // Alpha test threshold
      "Never";  // Alpha test function
      0;  // Perform final alpha write
      1.000000;  // Final alpha value
    }
    MaskDiffuseBlendsByDetailBlendMask  {
      0;
    }
    MaskFinalAlphaBlendByDetailBlendMask  {
      0;
    }
    EnhancedParameters  {
      0;  // Assume vertical normal
      0;  // Z-Write alpha
      0;  // No Z-Write 
      0;  // Volume shadow (deprecated)
      0;  // No shadow
      0;  // Prelit vertices
    }
    BaseMaterialSkin {
      0;  // Skinned
    }
    DoubleSidedMaterial {
      0;  // Double sided
    }
    BlendConstantSetting {
      0;  // Blend constant
    }
    ForceTextureAddressWrapSetting {
      0;  // Force texture address wrap
    }
    ForceTextureAddressClampSetting {
      0;  // Force texture address clamp
    }
    BaseMaterialSpecular {
      1;  // AllowBaseMaterialSpecular
    }
    NoSpecularBloom {
      1;  // AllowSpecularBloom
    }
    EmissiveBloom {
      0;  // AllowEmissiveBloom
    }
    AmbientLightScale  {
      1.000000;
    }
    ZBiasValue  {
      0.000000; // User Defined ZBias
    }
    MaterialScript  {
      "TemperatureScaleScript.lua"; // User Defined Material Script
    }
    UseEmissiveAlphaAsHeatMap {
      1;  // Use Emissive Alpha as Heat Map
    }
    TemperatureScale  {
      1.000000; // Temperature Scale
    }
    DetailColor  {
      1.000000; 1.000000; 1.000000; 1.000000;; // Detail Color
    }
    DetailTextureParameters  {
      0.000000;  // Detail Offset U
      0.000000;  // Detail Offset V
      0.000000;  // Detail Rotation
      1.000000;  // Detail Scale V
      "Multiply";  // Detail Blend Mode
      1.000000;  // Detail Blend Weight
      0;  // Use Detail Alpha as Blend Mask
    }
    DiffuseTextureFileName  {
      "IRSceneryObject_t.dds";
    }
    DiffuseTextureUVChannel  {
      1; // UV Channel to use for diffuse texture
    }
    EmissiveTextureFileName  {
      "IRSceneryObject_t_lm.dds";
    }
    EmissiveTextureUVChannel  {
      1; // UV Channel to use for Emissive texture
    }
  }
 // End P3DMaterial
}		// End Material 'House0'
}		// End MaterialList for 'Building'
MeshNormals {		// Mesh normals for Building
10;		// 10 vertex normals
  0.000000; 0.000000; 1.000000;,
  0.000000; 0.000000; -1.000000;,
  0.000000; -1.000000; -0.000000;,
  1.000000; 0.000000; -0.000000;,
  0.000000; 1.000000; -0.000000;,
  -1.000000; 0.000000; -0.000000;,
  0.000000; -0.813667; -0.581331;,
  0.573369; 0.000000; -0.819297;,
  0.000000; 0.813667; -0.581331;,
  -0.573369; 0.000000; -0.819297;;
20;		// 20 faces with normals
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 1, 1, 1;,
  3; 1, 1, 1;,
  3; 2, 2, 2;,
  3; 2, 2, 2;,
  3; 3, 3, 3;,
  3; 3, 3, 3;,
  3; 4, 4, 4;,
  3; 4, 4, 4;,
  3; 5, 5, 5;,
  3; 5, 5, 5;,
  3; 6, 6, 6;,
  3; 6, 6, 6;,
  3; 7, 7, 7;,
  3; 7, 7, 7;,
  3; 8, 8, 8;,
  3; 8, 8, 8;,
  3; 9, 9, 9;,
  3; 9, 9, 9;;
}		// End Mesh normals for Building
  MeshTextureCoords {
  41;		// 41 uv pairs
  1.000000; 0.834242;,
  0.000000; 0.834242;,
  1.000000; -0.165758;,
  0.000000; -0.165758;,
  0.852492; 0.999303;,
  0.852492; -0.000697;,
  0.852492; -0.000697;,
  0.658274; 0.772173;,
  0.218973; 0.271740;,
  0.636479; 0.271740;,
  0.218973; 0.095204;,
  0.636479; 0.095205;,
  0.998290; 0.999303;,
  0.998290; -0.000697;,
  0.998290; 0.999303;,
  0.048922; 0.996672;,
  0.658274; 0.996672;,
  0.048922; 0.772173;,
  0.048922; 0.996672;,
  0.998290; 0.999303;,
  0.998290; -0.000697;,
  0.852492; 0.999303;,
  0.998290; 0.999303;,
  0.048885; 0.996672;,
  0.658238; 0.996672;,
  0.658238; 0.772173;,
  0.658238; 0.772173;,
  0.048885; 0.772173;,
  0.048885; 0.996672;,
  0.010119; 0.360050;,
  0.845333; 0.360050;,
  0.010119; 0.360050;,
  0.845333; 0.360050;,
  0.845333; 0.006894;,
  0.845333; 0.360050;,
  0.845333; 0.006894;,
  0.010119; 0.006894;,
  0.845333; 0.006894;,
  0.010119; 0.006894;,
  0.010119; 0.360050;,
  0.010119; 0.006894;;
  }		// End MeshTexture Coords for 'Building'
}		// End of Mesh 'Building'

AnimLinkName { //Building 
    "Building";
}
}		 // End of frame frm-Building

Frame frm-Chimney {
FrameTransformMatrix {
  1.000000, 0.000000, -0.000000, 0.0,
  0.000000, 1.000000, -0.000000, 0.0,
  -0.000000, -0.000000, 1.000000, 0.0,
  -7.500000, 0.000000, -4.500000, 1.0;;
}		// End FrameTransformMatrix

Mesh Chimney {
26;		// Mesh 'Chimney' contains 26 vertices
  -0.500000; -0.500000; -0.000000;,
  0.500000; -0.500000; -0.000000;,
  -0.500000; 0.500000; -0.000000;,
  0.500000; 0.500000; -0.000000;,
  -0.500000; -0.500000; -5.000000;,
  0.500000; -0.500000; -5.000000;,
  -0.500000; 0.500000; -5.000000;,
  0.500000; 0.500000; -5.000000;,
  -0.500000; -0.500000; -0.000000;,
  0.500000; -0.500000; -0.000000;,
  0.500000; -0.500000; -5.000000;,
  0.500000; -0.500000; -5.000000;,
  -0.500000; -0.500000; -5.000000;,
  -0.500000; -0.500000; -0.000000;,
  0.500000; 0.500000; -0.000000;,
  0.500000; -0.500000; -5.000000;,
  0.500000; 0.500000; -0.000000;,
  -0.500000; 0.500000; -0.000000;,
  -0.500000; 0.500000; -5.000000;,
  -0.500000; 0.500000; -5.000000;,
  0.500000; 0.500000; -5.000000;,
  0.500000; 0.500000; -0.000000;,
  -0.500000; 0.500000; -0.000000;,
  -0.500000; -0.500000; -5.000000;,
  -0.500000; -0.500000; -5.000000;,
  -0.500000; 0.500000; -0.000000;;

12;		// Mesh 'Chimney' contains 12 Faces
  3; 3, 2, 0;,
  3; 0, 1, 3;,
  3; 7, 5, 4;,
  3; 4, 6, 7;,
  3; 10, 9, 8;,
  3; 13, 12, 11;,
  3; 7, 14, 1;,
  3; 1, 15, 7;,
  3; 18, 17, 16;,
  3; 21, 20, 19;,
  3; 23, 0, 22;,
  3; 25, 6, 24;;
MeshMaterialList {
  1; // 1 Materials
  12; // 12 Faces have materials specified
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0;
  Material House0 {
  0.588000; 0.588000; 0.588000; 1.000000;;
  0.000000;
  0.900000; 0.900000; 0.900000;;
  0.000000; 0.000000; 0.000000;;
  TextureFileName {
     "IRSceneryObject_t.dds";
  }
  DiffuseTextureFileName  {
    "IRSceneryObject_t.dds";
  }
  EmissiveTextureFileName  {
    "IRSceneryObject_t_lm.dds";
  }
  P3DMaterial {
    0.588000; 0.588000; 0.588000; 1.000000;; // Diffuse component
    0.900000; 0.900000; 0.900000;;     // Specular component
    0.000000;              // Specular power
    1.000000; 1.000000;          // Detail scale U and bump scale
    1.000000;              // Scale environment level factor
    0;              // Do not use global environment
    0;              // Do not blend env by inv diffuse alpha
    0;              // Do not blend env by specular map alpha
    0; 0; 0;      // Fresnel - diffuse = NO, Specular = NO, Env = NO
    0; 0; 0.000000;      // Precipitation - Use = NO, Offset = NO
    64.000000;              // Specular Map Power Scale
    "One"; "Zero";  // Src/Dest blend
    BlendDiffuseByBaseAlpha  {
      0;
    }
    BlendDiffuseByInverseSpecularMapAlpha  {
      0;
    }
    AllowBloom  {
      1;
    }
    SpecularBloomFloor  {
      0.900000;
    }
    EmissiveData  {
      "AdditiveNightOnly";  // Emissive mode
    }
    AlphaData  {
      0;  // ZTest Alpha
      0.000000;  // Alpha test threshold
      "Never";  // Alpha test function
      0;  // Perform final alpha write
      1.000000;  // Final alpha value
    }
    MaskDiffuseBlendsByDetailBlendMask  {
      0;
    }
    MaskFinalAlphaBlendByDetailBlendMask  {
      0;
    }
    EnhancedParameters  {
      0;  // Assume vertical normal
      0;  // Z-Write alpha
      0;  // No Z-Write 
      0;  // Volume shadow (deprecated)
      0;  // No shadow
      0;  // Prelit vertices
    }
    BaseMaterialSkin {
      0;  // Skinned
    }
    DoubleSidedMaterial {
      0;  // Double sided
    }
    BlendConstantSetting {
      0;  // Blend constant
    }
    ForceTextureAddressWrapSetting {
      0;  // Force texture address wrap
    }
    ForceTextureAddressClampSetting {
      0;  // Force texture address clamp
    }
    BaseMaterialSpecular {
      1;  // AllowBaseMaterialSpecular
    }
    NoSpecularBloom {
      1;  // AllowSpecularBloom
    }
    EmissiveBloom {
      0;  // AllowEmissiveBloom
    }
    AmbientLightScale  {
      1.000000;
    }
    ZBiasValue  {
      0.000000; // User Defined ZBias
    }
    MaterialScript  {
      "TemperatureScaleScript.lua"; // User Defined Material Script
    }
    UseEmissiveAlphaAsHeatMap {
      1;  // Use Emissive Alpha as Heat Map
    }
    TemperatureScale  {
      1.000000; // Temperature Scale
    }
    DetailColor  {
      1.000000; 1.000000; 1.000000; 1.000000;; // Detail Color
    }
    DetailTextureParameters  {
      0.000000;  // Detail Offset U
      0.000000;  // Detail Offset V
      0.000000;  // Detail Rotation
      1.000000;  // Detail Scale V
      "Multiply";  // Detail Blend Mode
      1.000000;  // Detail Blend Weight
      0;  // Use Detail Alpha as Blend Mask
    }
    DiffuseTextureFileName  {
      "IRSceneryObject_t.dds";
    }
    DiffuseTextureUVChannel  {
      1; // UV Channel to use for diffuse texture
    }
    EmissiveTextureFileName  {
      "IRSceneryObject_t_lm.dds";
    }
    EmissiveTextureUVChannel  {
      1; // UV Channel to use for Emissive texture
    }
  }
 // End P3DMaterial
}		// End Material 'House0'
}		// End MaterialList for 'Chimney'
MeshNormals {		// Mesh normals for Chimney
6;		// 6 vertex normals
  0.000000; 0.000000; 1.000000;,
  0.000000; 0.000000; -1.000000;,
  0.000000; -1.000000; -0.000000;,
  1.000000; 0.000000; -0.000000;,
  0.000000; 1.000000; -0.000000;,
  -1.000000; 0.000000; -0.000000;;
12;		// 12 faces with normals
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 1, 1, 1;,
  3; 1, 1, 1;,
  3; 2, 2, 2;,
  3; 2, 2, 2;,
  3; 3, 3, 3;,
  3; 3, 3, 3;,
  3; 4, 4, 4;,
  3; 4, 4, 4;,
  3; 5, 5, 5;,
  3; 5, 5, 5;;
}		// End Mesh normals for Chimney
  MeshTextureCoords {
  26;		// 26 uv pairs
  0.832324; 0.574173;,
  0.739693; 0.574173;,
  0.832324; 0.481541;,
  0.739693; 0.481541;,
  0.739693; 0.574173;,
  0.832324; 0.574173;,
  0.739693; 0.481541;,
  0.832324; 0.481541;,
  0.739693; 0.574173;,
  0.832324; 0.574173;,
  0.832324; 0.481541;,
  0.832324; 0.481541;,
  0.739693; 0.481541;,
  0.739693; 0.574173;,
  0.832324; 0.574173;,
  0.739693; 0.481541;,
  0.739693; 0.574173;,
  0.832324; 0.574173;,
  0.832324; 0.481541;,
  0.832324; 0.481541;,
  0.739693; 0.481541;,
  0.739693; 0.574173;,
  0.739693; 0.574173;,
  0.832324; 0.481541;,
  0.832324; 0.481541;,
  0.739693; 0.574173;;
  }		// End MeshTexture Coords for 'Chimney'
}		// End of Mesh 'Chimney'

AnimLinkName { //Chimney 
    "Chimney";
}
}		 // End of frame frm-Chimney

Frame frm-Barrel2 {
FrameTransformMatrix {
  1.000000, 0.000000, -0.000000, 0.0,
  0.000000, 1.000000, -0.000000, 0.0,
  -0.000000, -0.000000, 1.000000, 0.0,
  6.000000, -6.000000, -0.000000, 1.0;;
}		// End FrameTransformMatrix

Mesh Barrel2 {
43;		// Mesh 'Barrel2' contains 43 vertices
  0.000000; 0.000000; -0.000000;,
  0.500000; 0.000000; -0.000000;,
  0.469846; 0.171010; -0.000000;,
  0.383022; 0.321394; -0.000000;,
  0.250000; 0.433013; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  -0.086824; 0.492404; -0.000000;,
  -0.250000; 0.433013; -0.000000;,
  -0.383022; 0.321394; -0.000000;,
  -0.469846; 0.171010; -0.000000;,
  -0.500000; 0.000000; -0.000000;,
  -0.469846; -0.171010; -0.000000;,
  -0.383022; -0.321394; -0.000000;,
  -0.250000; -0.433013; -0.000000;,
  -0.086824; -0.492404; -0.000000;,
  0.086824; -0.492404; -0.000000;,
  0.250000; -0.433013; -0.000000;,
  0.383022; -0.321394; -0.000000;,
  0.469846; -0.171010; -0.000000;,
  0.500000; 0.000000; -1.500000;,
  0.469846; 0.171010; -1.500000;,
  0.383022; 0.321394; -1.500000;,
  0.250000; 0.433013; -1.500000;,
  0.086824; 0.492404; -1.500000;,
  -0.086824; 0.492404; -1.500000;,
  -0.250000; 0.433013; -1.500000;,
  -0.383022; 0.321394; -1.500000;,
  -0.469846; 0.171010; -1.500000;,
  -0.500000; 0.000000; -1.500000;,
  -0.469846; -0.171010; -1.500000;,
  -0.383022; -0.321394; -1.500000;,
  -0.250000; -0.433013; -1.500000;,
  -0.086824; -0.492404; -1.500000;,
  0.086824; -0.492404; -1.500000;,
  0.250000; -0.433013; -1.500000;,
  0.383022; -0.321394; -1.500000;,
  0.469846; -0.171010; -1.500000;,
  0.000000; 0.000000; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;;

72;		// Mesh 'Barrel2' contains 72 Faces
  3; 1, 2, 0;,
  3; 2, 3, 0;,
  3; 3, 4, 0;,
  3; 4, 5, 0;,
  3; 38, 6, 0;,
  3; 6, 7, 0;,
  3; 7, 8, 0;,
  3; 8, 9, 0;,
  3; 9, 10, 0;,
  3; 10, 11, 0;,
  3; 11, 12, 0;,
  3; 12, 13, 0;,
  3; 13, 14, 0;,
  3; 14, 15, 0;,
  3; 15, 16, 0;,
  3; 16, 17, 0;,
  3; 17, 18, 0;,
  3; 18, 1, 0;,
  3; 19, 20, 1;,
  3; 20, 2, 1;,
  3; 20, 21, 2;,
  3; 21, 3, 2;,
  3; 21, 22, 3;,
  3; 22, 4, 3;,
  3; 22, 23, 4;,
  3; 23, 5, 4;,
  3; 40, 24, 39;,
  3; 24, 6, 41;,
  3; 24, 25, 6;,
  3; 25, 7, 6;,
  3; 25, 26, 7;,
  3; 26, 8, 7;,
  3; 26, 27, 8;,
  3; 27, 9, 8;,
  3; 27, 28, 9;,
  3; 28, 10, 9;,
  3; 28, 29, 10;,
  3; 29, 11, 10;,
  3; 29, 30, 11;,
  3; 30, 12, 11;,
  3; 30, 31, 12;,
  3; 31, 13, 12;,
  3; 31, 32, 13;,
  3; 32, 14, 13;,
  3; 32, 33, 14;,
  3; 33, 15, 14;,
  3; 33, 34, 15;,
  3; 34, 16, 15;,
  3; 34, 35, 16;,
  3; 35, 17, 16;,
  3; 35, 36, 17;,
  3; 36, 18, 17;,
  3; 36, 19, 18;,
  3; 19, 1, 18;,
  3; 20, 19, 37;,
  3; 21, 20, 37;,
  3; 22, 21, 37;,
  3; 23, 22, 37;,
  3; 24, 42, 37;,
  3; 25, 24, 37;,
  3; 26, 25, 37;,
  3; 27, 26, 37;,
  3; 28, 27, 37;,
  3; 29, 28, 37;,
  3; 30, 29, 37;,
  3; 31, 30, 37;,
  3; 32, 31, 37;,
  3; 33, 32, 37;,
  3; 34, 33, 37;,
  3; 35, 34, 37;,
  3; 36, 35, 37;,
  3; 19, 36, 37;;
MeshMaterialList {
  1; // 1 Materials
  72; // 72 Faces have materials specified
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0;
  Material House0 {
  0.588000; 0.588000; 0.588000; 1.000000;;
  0.000000;
  0.900000; 0.900000; 0.900000;;
  0.000000; 0.000000; 0.000000;;
  TextureFileName {
     "IRSceneryObject_t.dds";
  }
  DiffuseTextureFileName  {
    "IRSceneryObject_t.dds";
  }
  EmissiveTextureFileName  {
    "IRSceneryObject_t_lm.dds";
  }
  P3DMaterial {
    0.588000; 0.588000; 0.588000; 1.000000;; // Diffuse component
    0.900000; 0.900000; 0.900000;;     // Specular component
    0.000000;              // Specular power
    1.000000; 1.000000;          // Detail scale U and bump scale
    1.000000;              // Scale environment level factor
    0;              // Do not use global environment
    0;              // Do not blend env by inv diffuse alpha
    0;              // Do not blend env by specular map alpha
    0; 0; 0;      // Fresnel - diffuse = NO, Specular = NO, Env = NO
    0; 0; 0.000000;      // Precipitation - Use = NO, Offset = NO
    64.000000;              // Specular Map Power Scale
    "One"; "Zero";  // Src/Dest blend
    BlendDiffuseByBaseAlpha  {
      0;
    }
    BlendDiffuseByInverseSpecularMapAlpha  {
      0;
    }
    AllowBloom  {
      1;
    }
    SpecularBloomFloor  {
      0.900000;
    }
    EmissiveData  {
      "AdditiveNightOnly";  // Emissive mode
    }
    AlphaData  {
      0;  // ZTest Alpha
      0.000000;  // Alpha test threshold
      "Never";  // Alpha test function
      0;  // Perform final alpha write
      1.000000;  // Final alpha value
    }
    MaskDiffuseBlendsByDetailBlendMask  {
      0;
    }
    MaskFinalAlphaBlendByDetailBlendMask  {
      0;
    }
    EnhancedParameters  {
      0;  // Assume vertical normal
      0;  // Z-Write alpha
      0;  // No Z-Write 
      0;  // Volume shadow (deprecated)
      0;  // No shadow
      0;  // Prelit vertices
    }
    BaseMaterialSkin {
      0;  // Skinned
    }
    DoubleSidedMaterial {
      0;  // Double sided
    }
    BlendConstantSetting {
      0;  // Blend constant
    }
    ForceTextureAddressWrapSetting {
      0;  // Force texture address wrap
    }
    ForceTextureAddressClampSetting {
      0;  // Force texture address clamp
    }
    BaseMaterialSpecular {
      1;  // AllowBaseMaterialSpecular
    }
    NoSpecularBloom {
      1;  // AllowSpecularBloom
    }
    EmissiveBloom {
      0;  // AllowEmissiveBloom
    }
    AmbientLightScale  {
      1.000000;
    }
    ZBiasValue  {
      0.000000; // User Defined ZBias
    }
    MaterialScript  {
      "TemperatureScaleScript.lua"; // User Defined Material Script
    }
    UseEmissiveAlphaAsHeatMap {
      1;  // Use Emissive Alpha as Heat Map
    }
    TemperatureScale  {
      1.000000; // Temperature Scale
    }
    DetailColor  {
      1.000000; 1.000000; 1.000000; 1.000000;; // Detail Color
    }
    DetailTextureParameters  {
      0.000000;  // Detail Offset U
      0.000000;  // Detail Offset V
      0.000000;  // Detail Rotation
      1.000000;  // Detail Scale V
      "Multiply";  // Detail Blend Mode
      1.000000;  // Detail Blend Weight
      0;  // Use Detail Alpha as Blend Mask
    }
    DiffuseTextureFileName  {
      "IRSceneryObject_t.dds";
    }
    DiffuseTextureUVChannel  {
      1; // UV Channel to use for diffuse texture
    }
    EmissiveTextureFileName  {
      "IRSceneryObject_t_lm.dds";
    }
    EmissiveTextureUVChannel  {
      1; // UV Channel to use for Emissive texture
    }
  }
 // End P3DMaterial
}		// End Material 'House0'
}		// End MaterialList for 'Barrel2'
MeshNormals {		// Mesh normals for Barrel2
20;		// 20 vertex normals
  0.000000; 0.000000; 1.000000;,
  1.000000; -0.000000; -0.000000;,
  0.939693; 0.342020; -0.000000;,
  0.766044; 0.642788; -0.000000;,
  0.500000; 0.866025; -0.000000;,
  0.173648; 0.984808; -0.000000;,
  -0.173648; 0.984808; -0.000000;,
  -0.500000; 0.866025; -0.000000;,
  -0.766044; 0.642788; -0.000000;,
  -0.939693; 0.342020; -0.000000;,
  -1.000000; 0.000000; -0.000000;,
  -0.939693; -0.342020; -0.000000;,
  -0.766045; -0.642787; -0.000000;,
  -0.500000; -0.866025; -0.000000;,
  -0.173649; -0.984808; -0.000000;,
  0.173648; -0.984808; -0.000000;,
  0.499999; -0.866026; -0.000000;,
  0.766044; -0.642788; -0.000000;,
  0.939692; -0.342021; -0.000000;,
  0.000000; 0.000000; -1.000000;;
72;		// 72 faces with normals
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 1, 2, 1;,
  3; 2, 2, 1;,
  3; 2, 3, 2;,
  3; 3, 3, 2;,
  3; 3, 4, 3;,
  3; 4, 4, 3;,
  3; 4, 5, 4;,
  3; 5, 5, 4;,
  3; 5, 6, 5;,
  3; 6, 6, 5;,
  3; 6, 7, 6;,
  3; 7, 7, 6;,
  3; 7, 8, 7;,
  3; 8, 8, 7;,
  3; 8, 9, 8;,
  3; 9, 9, 8;,
  3; 9, 10, 9;,
  3; 10, 10, 9;,
  3; 10, 11, 10;,
  3; 11, 11, 10;,
  3; 11, 12, 11;,
  3; 12, 12, 11;,
  3; 12, 13, 12;,
  3; 13, 13, 12;,
  3; 13, 14, 13;,
  3; 14, 14, 13;,
  3; 14, 15, 14;,
  3; 15, 15, 14;,
  3; 15, 16, 15;,
  3; 16, 16, 15;,
  3; 16, 17, 16;,
  3; 17, 17, 16;,
  3; 17, 18, 17;,
  3; 18, 18, 17;,
  3; 18, 1, 18;,
  3; 1, 1, 18;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;;
}		// End Mesh normals for Barrel2
  MeshTextureCoords {
  43;		// 43 uv pairs
  0.769079; 0.995429;,
  0.795585; 0.995429;,
  0.801393; 0.995429;,
  0.807239; 0.995429;,
  0.813144; 0.995429;,
  0.819102; 0.995429;,
  0.719056; 0.995429;,
  0.725014; 0.995429;,
  0.730919; 0.995429;,
  0.736765; 0.995429;,
  0.742573; 0.995429;,
  0.748381; 0.995429;,
  0.754226; 0.995429;,
  0.760131; 0.995429;,
  0.766089; 0.995429;,
  0.772069; 0.995429;,
  0.778027; 0.995429;,
  0.783932; 0.995429;,
  0.789778; 0.995429;,
  0.795585; 0.812627;,
  0.801393; 0.812627;,
  0.807239; 0.812627;,
  0.813144; 0.812627;,
  0.819102; 0.812627;,
  0.719056; 0.812627;,
  0.725014; 0.812627;,
  0.730919; 0.812627;,
  0.736765; 0.812627;,
  0.742573; 0.812627;,
  0.748381; 0.812627;,
  0.754226; 0.812627;,
  0.760131; 0.812627;,
  0.766089; 0.812627;,
  0.772069; 0.812627;,
  0.778027; 0.812627;,
  0.783932; 0.812627;,
  0.789778; 0.812627;,
  0.769079; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.995429;,
  0.713077; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.812627;;
  }		// End MeshTexture Coords for 'Barrel2'
}		// End of Mesh 'Barrel2'

AnimLinkName { //Barrel2 
    "Barrel2";
}
}		 // End of frame frm-Barrel2

Frame frm-Barrel0 {
FrameTransformMatrix {
  1.000000, 0.000000, -0.000000, 0.0,
  0.000000, 1.000000, -0.000000, 0.0,
  -0.000000, -0.000000, 1.000000, 0.0,
  4.000000, -6.000000, -0.000000, 1.0;;
}		// End FrameTransformMatrix

Mesh Barrel0 {
43;		// Mesh 'Barrel0' contains 43 vertices
  0.000000; 0.000000; -0.000000;,
  0.500000; 0.000000; -0.000000;,
  0.469846; 0.171010; -0.000000;,
  0.383022; 0.321394; -0.000000;,
  0.250000; 0.433013; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  -0.086824; 0.492404; -0.000000;,
  -0.250000; 0.433013; -0.000000;,
  -0.383022; 0.321394; -0.000000;,
  -0.469846; 0.171010; -0.000000;,
  -0.500000; 0.000000; -0.000000;,
  -0.469846; -0.171010; -0.000000;,
  -0.383022; -0.321394; -0.000000;,
  -0.250000; -0.433013; -0.000000;,
  -0.086824; -0.492404; -0.000000;,
  0.086824; -0.492404; -0.000000;,
  0.250000; -0.433013; -0.000000;,
  0.383022; -0.321394; -0.000000;,
  0.469846; -0.171010; -0.000000;,
  0.500000; 0.000000; -1.500000;,
  0.469846; 0.171010; -1.500000;,
  0.383022; 0.321394; -1.500000;,
  0.250000; 0.433013; -1.500000;,
  0.086824; 0.492404; -1.500000;,
  -0.086824; 0.492404; -1.500000;,
  -0.250000; 0.433013; -1.500000;,
  -0.383022; 0.321394; -1.500000;,
  -0.469846; 0.171010; -1.500000;,
  -0.500000; 0.000000; -1.500000;,
  -0.469846; -0.171010; -1.500000;,
  -0.383022; -0.321394; -1.500000;,
  -0.250000; -0.433013; -1.500000;,
  -0.086824; -0.492404; -1.500000;,
  0.086824; -0.492404; -1.500000;,
  0.250000; -0.433013; -1.500000;,
  0.383022; -0.321394; -1.500000;,
  0.469846; -0.171010; -1.500000;,
  0.000000; 0.000000; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;;

72;		// Mesh 'Barrel0' contains 72 Faces
  3; 1, 2, 0;,
  3; 2, 3, 0;,
  3; 3, 4, 0;,
  3; 4, 5, 0;,
  3; 38, 6, 0;,
  3; 6, 7, 0;,
  3; 7, 8, 0;,
  3; 8, 9, 0;,
  3; 9, 10, 0;,
  3; 10, 11, 0;,
  3; 11, 12, 0;,
  3; 12, 13, 0;,
  3; 13, 14, 0;,
  3; 14, 15, 0;,
  3; 15, 16, 0;,
  3; 16, 17, 0;,
  3; 17, 18, 0;,
  3; 18, 1, 0;,
  3; 19, 20, 1;,
  3; 20, 2, 1;,
  3; 20, 21, 2;,
  3; 21, 3, 2;,
  3; 21, 22, 3;,
  3; 22, 4, 3;,
  3; 22, 23, 4;,
  3; 23, 5, 4;,
  3; 40, 24, 39;,
  3; 24, 6, 41;,
  3; 24, 25, 6;,
  3; 25, 7, 6;,
  3; 25, 26, 7;,
  3; 26, 8, 7;,
  3; 26, 27, 8;,
  3; 27, 9, 8;,
  3; 27, 28, 9;,
  3; 28, 10, 9;,
  3; 28, 29, 10;,
  3; 29, 11, 10;,
  3; 29, 30, 11;,
  3; 30, 12, 11;,
  3; 30, 31, 12;,
  3; 31, 13, 12;,
  3; 31, 32, 13;,
  3; 32, 14, 13;,
  3; 32, 33, 14;,
  3; 33, 15, 14;,
  3; 33, 34, 15;,
  3; 34, 16, 15;,
  3; 34, 35, 16;,
  3; 35, 17, 16;,
  3; 35, 36, 17;,
  3; 36, 18, 17;,
  3; 36, 19, 18;,
  3; 19, 1, 18;,
  3; 20, 19, 37;,
  3; 21, 20, 37;,
  3; 22, 21, 37;,
  3; 23, 22, 37;,
  3; 24, 42, 37;,
  3; 25, 24, 37;,
  3; 26, 25, 37;,
  3; 27, 26, 37;,
  3; 28, 27, 37;,
  3; 29, 28, 37;,
  3; 30, 29, 37;,
  3; 31, 30, 37;,
  3; 32, 31, 37;,
  3; 33, 32, 37;,
  3; 34, 33, 37;,
  3; 35, 34, 37;,
  3; 36, 35, 37;,
  3; 19, 36, 37;;
MeshMaterialList {
  1; // 1 Materials
  72; // 72 Faces have materials specified
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0;
  Material House0 {
  0.588000; 0.588000; 0.588000; 1.000000;;
  0.000000;
  0.900000; 0.900000; 0.900000;;
  0.000000; 0.000000; 0.000000;;
  TextureFileName {
     "IRSceneryObject_t.dds";
  }
  DiffuseTextureFileName  {
    "IRSceneryObject_t.dds";
  }
  EmissiveTextureFileName  {
    "IRSceneryObject_t_lm.dds";
  }
  P3DMaterial {
    0.588000; 0.588000; 0.588000; 1.000000;; // Diffuse component
    0.900000; 0.900000; 0.900000;;     // Specular component
    0.000000;              // Specular power
    1.000000; 1.000000;          // Detail scale U and bump scale
    1.000000;              // Scale environment level factor
    0;              // Do not use global environment
    0;              // Do not blend env by inv diffuse alpha
    0;              // Do not blend env by specular map alpha
    0; 0; 0;      // Fresnel - diffuse = NO, Specular = NO, Env = NO
    0; 0; 0.000000;      // Precipitation - Use = NO, Offset = NO
    64.000000;              // Specular Map Power Scale
    "One"; "Zero";  // Src/Dest blend
    BlendDiffuseByBaseAlpha  {
      0;
    }
    BlendDiffuseByInverseSpecularMapAlpha  {
      0;
    }
    AllowBloom  {
      1;
    }
    SpecularBloomFloor  {
      0.900000;
    }
    EmissiveData  {
      "AdditiveNightOnly";  // Emissive mode
    }
    AlphaData  {
      0;  // ZTest Alpha
      0.000000;  // Alpha test threshold
      "Never";  // Alpha test function
      0;  // Perform final alpha write
      1.000000;  // Final alpha value
    }
    MaskDiffuseBlendsByDetailBlendMask  {
      0;
    }
    MaskFinalAlphaBlendByDetailBlendMask  {
      0;
    }
    EnhancedParameters  {
      0;  // Assume vertical normal
      0;  // Z-Write alpha
      0;  // No Z-Write 
      0;  // Volume shadow (deprecated)
      0;  // No shadow
      0;  // Prelit vertices
    }
    BaseMaterialSkin {
      0;  // Skinned
    }
    DoubleSidedMaterial {
      0;  // Double sided
    }
    BlendConstantSetting {
      0;  // Blend constant
    }
    ForceTextureAddressWrapSetting {
      0;  // Force texture address wrap
    }
    ForceTextureAddressClampSetting {
      0;  // Force texture address clamp
    }
    BaseMaterialSpecular {
      1;  // AllowBaseMaterialSpecular
    }
    NoSpecularBloom {
      1;  // AllowSpecularBloom
    }
    EmissiveBloom {
      0;  // AllowEmissiveBloom
    }
    AmbientLightScale  {
      1.000000;
    }
    ZBiasValue  {
      0.000000; // User Defined ZBias
    }
    MaterialScript  {
      "TemperatureScaleScript.lua"; // User Defined Material Script
    }
    UseEmissiveAlphaAsHeatMap {
      1;  // Use Emissive Alpha as Heat Map
    }
    TemperatureScale  {
      1.000000; // Temperature Scale
    }
    DetailColor  {
      1.000000; 1.000000; 1.000000; 1.000000;; // Detail Color
    }
    DetailTextureParameters  {
      0.000000;  // Detail Offset U
      0.000000;  // Detail Offset V
      0.000000;  // Detail Rotation
      1.000000;  // Detail Scale V
      "Multiply";  // Detail Blend Mode
      1.000000;  // Detail Blend Weight
      0;  // Use Detail Alpha as Blend Mask
    }
    DiffuseTextureFileName  {
      "IRSceneryObject_t.dds";
    }
    DiffuseTextureUVChannel  {
      1; // UV Channel to use for diffuse texture
    }
    EmissiveTextureFileName  {
      "IRSceneryObject_t_lm.dds";
    }
    EmissiveTextureUVChannel  {
      1; // UV Channel to use for Emissive texture
    }
  }
 // End P3DMaterial
}		// End Material 'House0'
}		// End MaterialList for 'Barrel0'
MeshNormals {		// Mesh normals for Barrel0
20;		// 20 vertex normals
  0.000000; 0.000000; 1.000000;,
  1.000000; -0.000000; -0.000000;,
  0.939693; 0.342020; -0.000000;,
  0.766044; 0.642788; -0.000000;,
  0.500000; 0.866025; -0.000000;,
  0.173648; 0.984808; -0.000000;,
  -0.173648; 0.984808; -0.000000;,
  -0.500000; 0.866025; -0.000000;,
  -0.766044; 0.642788; -0.000000;,
  -0.939693; 0.342020; -0.000000;,
  -1.000000; 0.000000; -0.000000;,
  -0.939693; -0.342020; -0.000000;,
  -0.766045; -0.642787; -0.000000;,
  -0.500000; -0.866025; -0.000000;,
  -0.173649; -0.984808; -0.000000;,
  0.173648; -0.984808; -0.000000;,
  0.499999; -0.866026; -0.000000;,
  0.766044; -0.642788; -0.000000;,
  0.939692; -0.342021; -0.000000;,
  0.000000; 0.000000; -1.000000;;
72;		// 72 faces with normals
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 1, 2, 1;,
  3; 2, 2, 1;,
  3; 2, 3, 2;,
  3; 3, 3, 2;,
  3; 3, 4, 3;,
  3; 4, 4, 3;,
  3; 4, 5, 4;,
  3; 5, 5, 4;,
  3; 5, 6, 5;,
  3; 6, 6, 5;,
  3; 6, 7, 6;,
  3; 7, 7, 6;,
  3; 7, 8, 7;,
  3; 8, 8, 7;,
  3; 8, 9, 8;,
  3; 9, 9, 8;,
  3; 9, 10, 9;,
  3; 10, 10, 9;,
  3; 10, 11, 10;,
  3; 11, 11, 10;,
  3; 11, 12, 11;,
  3; 12, 12, 11;,
  3; 12, 13, 12;,
  3; 13, 13, 12;,
  3; 13, 14, 13;,
  3; 14, 14, 13;,
  3; 14, 15, 14;,
  3; 15, 15, 14;,
  3; 15, 16, 15;,
  3; 16, 16, 15;,
  3; 16, 17, 16;,
  3; 17, 17, 16;,
  3; 17, 18, 17;,
  3; 18, 18, 17;,
  3; 18, 1, 18;,
  3; 1, 1, 18;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;;
}		// End Mesh normals for Barrel0
  MeshTextureCoords {
  43;		// 43 uv pairs
  0.769079; 0.995429;,
  0.795585; 0.995429;,
  0.801393; 0.995429;,
  0.807239; 0.995429;,
  0.813144; 0.995429;,
  0.819102; 0.995429;,
  0.719056; 0.995429;,
  0.725014; 0.995429;,
  0.730919; 0.995429;,
  0.736765; 0.995429;,
  0.742573; 0.995429;,
  0.748381; 0.995429;,
  0.754226; 0.995429;,
  0.760131; 0.995429;,
  0.766089; 0.995429;,
  0.772069; 0.995429;,
  0.778027; 0.995429;,
  0.783932; 0.995429;,
  0.789778; 0.995429;,
  0.795585; 0.812627;,
  0.801393; 0.812627;,
  0.807239; 0.812627;,
  0.813144; 0.812627;,
  0.819102; 0.812627;,
  0.719056; 0.812627;,
  0.725014; 0.812627;,
  0.730919; 0.812627;,
  0.736765; 0.812627;,
  0.742573; 0.812627;,
  0.748381; 0.812627;,
  0.754226; 0.812627;,
  0.760131; 0.812627;,
  0.766089; 0.812627;,
  0.772069; 0.812627;,
  0.778027; 0.812627;,
  0.783932; 0.812627;,
  0.789778; 0.812627;,
  0.769079; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.995429;,
  0.713077; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.812627;;
  }		// End MeshTexture Coords for 'Barrel0'
}		// End of Mesh 'Barrel0'

AnimLinkName { //Barrel0 
    "Barrel0";
}
}		 // End of frame frm-Barrel0

Frame frm-Barrel1 {
FrameTransformMatrix {
  1.000000, 0.000000, -0.000000, 0.0,
  0.000000, 1.000000, -0.000000, 0.0,
  -0.000000, -0.000000, 1.000000, 0.0,
  5.000000, -7.000000, -0.000000, 1.0;;
}		// End FrameTransformMatrix

Mesh Barrel1 {
43;		// Mesh 'Barrel1' contains 43 vertices
  0.000000; 0.000000; -0.000000;,
  0.500000; 0.000000; -0.000000;,
  0.469846; 0.171010; -0.000000;,
  0.383022; 0.321394; -0.000000;,
  0.250000; 0.433013; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  -0.086824; 0.492404; -0.000000;,
  -0.250000; 0.433013; -0.000000;,
  -0.383022; 0.321394; -0.000000;,
  -0.469846; 0.171010; -0.000000;,
  -0.500000; 0.000000; -0.000000;,
  -0.469846; -0.171010; -0.000000;,
  -0.383022; -0.321394; -0.000000;,
  -0.250000; -0.433013; -0.000000;,
  -0.086824; -0.492404; -0.000000;,
  0.086824; -0.492404; -0.000000;,
  0.250000; -0.433013; -0.000000;,
  0.383022; -0.321394; -0.000000;,
  0.469846; -0.171010; -0.000000;,
  0.500000; 0.000000; -1.500000;,
  0.469846; 0.171010; -1.500000;,
  0.383022; 0.321394; -1.500000;,
  0.250000; 0.433013; -1.500000;,
  0.086824; 0.492404; -1.500000;,
  -0.086824; 0.492404; -1.500000;,
  -0.250000; 0.433013; -1.500000;,
  -0.383022; 0.321394; -1.500000;,
  -0.469846; 0.171010; -1.500000;,
  -0.500000; 0.000000; -1.500000;,
  -0.469846; -0.171010; -1.500000;,
  -0.383022; -0.321394; -1.500000;,
  -0.250000; -0.433013; -1.500000;,
  -0.086824; -0.492404; -1.500000;,
  0.086824; -0.492404; -1.500000;,
  0.250000; -0.433013; -1.500000;,
  0.383022; -0.321394; -1.500000;,
  0.469846; -0.171010; -1.500000;,
  0.000000; 0.000000; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;,
  0.086824; 0.492404; -0.000000;,
  0.086824; 0.492404; -1.500000;;

72;		// Mesh 'Barrel1' contains 72 Faces
  3; 1, 2, 0;,
  3; 2, 3, 0;,
  3; 3, 4, 0;,
  3; 4, 5, 0;,
  3; 38, 6, 0;,
  3; 6, 7, 0;,
  3; 7, 8, 0;,
  3; 8, 9, 0;,
  3; 9, 10, 0;,
  3; 10, 11, 0;,
  3; 11, 12, 0;,
  3; 12, 13, 0;,
  3; 13, 14, 0;,
  3; 14, 15, 0;,
  3; 15, 16, 0;,
  3; 16, 17, 0;,
  3; 17, 18, 0;,
  3; 18, 1, 0;,
  3; 19, 20, 1;,
  3; 20, 2, 1;,
  3; 20, 21, 2;,
  3; 21, 3, 2;,
  3; 21, 22, 3;,
  3; 22, 4, 3;,
  3; 22, 23, 4;,
  3; 23, 5, 4;,
  3; 40, 24, 39;,
  3; 24, 6, 41;,
  3; 24, 25, 6;,
  3; 25, 7, 6;,
  3; 25, 26, 7;,
  3; 26, 8, 7;,
  3; 26, 27, 8;,
  3; 27, 9, 8;,
  3; 27, 28, 9;,
  3; 28, 10, 9;,
  3; 28, 29, 10;,
  3; 29, 11, 10;,
  3; 29, 30, 11;,
  3; 30, 12, 11;,
  3; 30, 31, 12;,
  3; 31, 13, 12;,
  3; 31, 32, 13;,
  3; 32, 14, 13;,
  3; 32, 33, 14;,
  3; 33, 15, 14;,
  3; 33, 34, 15;,
  3; 34, 16, 15;,
  3; 34, 35, 16;,
  3; 35, 17, 16;,
  3; 35, 36, 17;,
  3; 36, 18, 17;,
  3; 36, 19, 18;,
  3; 19, 1, 18;,
  3; 20, 19, 37;,
  3; 21, 20, 37;,
  3; 22, 21, 37;,
  3; 23, 22, 37;,
  3; 24, 42, 37;,
  3; 25, 24, 37;,
  3; 26, 25, 37;,
  3; 27, 26, 37;,
  3; 28, 27, 37;,
  3; 29, 28, 37;,
  3; 30, 29, 37;,
  3; 31, 30, 37;,
  3; 32, 31, 37;,
  3; 33, 32, 37;,
  3; 34, 33, 37;,
  3; 35, 34, 37;,
  3; 36, 35, 37;,
  3; 19, 36, 37;;
MeshMaterialList {
  1; // 1 Materials
  72; // 72 Faces have materials specified
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0;
  Material House0 {
  0.588000; 0.588000; 0.588000; 1.000000;;
  0.000000;
  0.900000; 0.900000; 0.900000;;
  0.000000; 0.000000; 0.000000;;
  TextureFileName {
     "IRSceneryObject_t.dds";
  }
  DiffuseTextureFileName  {
    "IRSceneryObject_t.dds";
  }
  EmissiveTextureFileName  {
    "IRSceneryObject_t_lm.dds";
  }
  P3DMaterial {
    0.588000; 0.588000; 0.588000; 1.000000;; // Diffuse component
    0.900000; 0.900000; 0.900000;;     // Specular component
    0.000000;              // Specular power
    1.000000; 1.000000;          // Detail scale U and bump scale
    1.000000;              // Scale environment level factor
    0;              // Do not use global environment
    0;              // Do not blend env by inv diffuse alpha
    0;              // Do not blend env by specular map alpha
    0; 0; 0;      // Fresnel - diffuse = NO, Specular = NO, Env = NO
    0; 0; 0.000000;      // Precipitation - Use = NO, Offset = NO
    64.000000;              // Specular Map Power Scale
    "One"; "Zero";  // Src/Dest blend
    BlendDiffuseByBaseAlpha  {
      0;
    }
    BlendDiffuseByInverseSpecularMapAlpha  {
      0;
    }
    AllowBloom  {
      1;
    }
    SpecularBloomFloor  {
      0.900000;
    }
    EmissiveData  {
      "AdditiveNightOnly";  // Emissive mode
    }
    AlphaData  {
      0;  // ZTest Alpha
      0.000000;  // Alpha test threshold
      "Never";  // Alpha test function
      0;  // Perform final alpha write
      1.000000;  // Final alpha value
    }
    MaskDiffuseBlendsByDetailBlendMask  {
      0;
    }
    MaskFinalAlphaBlendByDetailBlendMask  {
      0;
    }
    EnhancedParameters  {
      0;  // Assume vertical normal
      0;  // Z-Write alpha
      0;  // No Z-Write 
      0;  // Volume shadow (deprecated)
      0;  // No shadow
      0;  // Prelit vertices
    }
    BaseMaterialSkin {
      0;  // Skinned
    }
    DoubleSidedMaterial {
      0;  // Double sided
    }
    BlendConstantSetting {
      0;  // Blend constant
    }
    ForceTextureAddressWrapSetting {
      0;  // Force texture address wrap
    }
    ForceTextureAddressClampSetting {
      0;  // Force texture address clamp
    }
    BaseMaterialSpecular {
      1;  // AllowBaseMaterialSpecular
    }
    NoSpecularBloom {
      1;  // AllowSpecularBloom
    }
    EmissiveBloom {
      0;  // AllowEmissiveBloom
    }
    AmbientLightScale  {
      1.000000;
    }
    ZBiasValue  {
      0.000000; // User Defined ZBias
    }
    MaterialScript  {
      "TemperatureScaleScript.lua"; // User Defined Material Script
    }
    UseEmissiveAlphaAsHeatMap {
      1;  // Use Emissive Alpha as Heat Map
    }
    TemperatureScale  {
      1.000000; // Temperature Scale
    }
    DetailColor  {
      1.000000; 1.000000; 1.000000; 1.000000;; // Detail Color
    }
    DetailTextureParameters  {
      0.000000;  // Detail Offset U
      0.000000;  // Detail Offset V
      0.000000;  // Detail Rotation
      1.000000;  // Detail Scale V
      "Multiply";  // Detail Blend Mode
      1.000000;  // Detail Blend Weight
      0;  // Use Detail Alpha as Blend Mask
    }
    DiffuseTextureFileName  {
      "IRSceneryObject_t.dds";
    }
    DiffuseTextureUVChannel  {
      1; // UV Channel to use for diffuse texture
    }
    EmissiveTextureFileName  {
      "IRSceneryObject_t_lm.dds";
    }
    EmissiveTextureUVChannel  {
      1; // UV Channel to use for Emissive texture
    }
  }
 // End P3DMaterial
}		// End Material 'House0'
}		// End MaterialList for 'Barrel1'
MeshNormals {		// Mesh normals for Barrel1
20;		// 20 vertex normals
  0.000000; 0.000000; 1.000000;,
  1.000000; -0.000000; -0.000000;,
  0.939693; 0.342020; -0.000000;,
  0.766044; 0.642788; -0.000000;,
  0.500000; 0.866025; -0.000000;,
  0.173648; 0.984808; -0.000000;,
  -0.173648; 0.984808; -0.000000;,
  -0.500000; 0.866025; -0.000000;,
  -0.766044; 0.642788; -0.000000;,
  -0.939693; 0.342020; -0.000000;,
  -1.000000; 0.000000; -0.000000;,
  -0.939693; -0.342020; -0.000000;,
  -0.766045; -0.642787; -0.000000;,
  -0.500000; -0.866025; -0.000000;,
  -0.173649; -0.984808; -0.000000;,
  0.173648; -0.984808; -0.000000;,
  0.499999; -0.866026; -0.000000;,
  0.766044; -0.642788; -0.000000;,
  0.939692; -0.342021; -0.000000;,
  0.000000; 0.000000; -1.000000;;
72;		// 72 faces with normals
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 0, 0, 0;,
  3; 1, 2, 1;,
  3; 2, 2, 1;,
  3; 2, 3, 2;,
  3; 3, 3, 2;,
  3; 3, 4, 3;,
  3; 4, 4, 3;,
  3; 4, 5, 4;,
  3; 5, 5, 4;,
  3; 5, 6, 5;,
  3; 6, 6, 5;,
  3; 6, 7, 6;,
  3; 7, 7, 6;,
  3; 7, 8, 7;,
  3; 8, 8, 7;,
  3; 8, 9, 8;,
  3; 9, 9, 8;,
  3; 9, 10, 9;,
  3; 10, 10, 9;,
  3; 10, 11, 10;,
  3; 11, 11, 10;,
  3; 11, 12, 11;,
  3; 12, 12, 11;,
  3; 12, 13, 12;,
  3; 13, 13, 12;,
  3; 13, 14, 13;,
  3; 14, 14, 13;,
  3; 14, 15, 14;,
  3; 15, 15, 14;,
  3; 15, 16, 15;,
  3; 16, 16, 15;,
  3; 16, 17, 16;,
  3; 17, 17, 16;,
  3; 17, 18, 17;,
  3; 18, 18, 17;,
  3; 18, 1, 18;,
  3; 1, 1, 18;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;,
  3; 19, 19, 19;;
}		// End Mesh normals for Barrel1
  MeshTextureCoords {
  43;		// 43 uv pairs
  0.769079; 0.995429;,
  0.795585; 0.995429;,
  0.801393; 0.995429;,
  0.807239; 0.995429;,
  0.813144; 0.995429;,
  0.819102; 0.995429;,
  0.719056; 0.995429;,
  0.725014; 0.995429;,
  0.730919; 0.995429;,
  0.736765; 0.995429;,
  0.742573; 0.995429;,
  0.748381; 0.995429;,
  0.754226; 0.995429;,
  0.760131; 0.995429;,
  0.766089; 0.995429;,
  0.772069; 0.995429;,
  0.778027; 0.995429;,
  0.783932; 0.995429;,
  0.789778; 0.995429;,
  0.795585; 0.812627;,
  0.801393; 0.812627;,
  0.807239; 0.812627;,
  0.813144; 0.812627;,
  0.819102; 0.812627;,
  0.719056; 0.812627;,
  0.725014; 0.812627;,
  0.730919; 0.812627;,
  0.736765; 0.812627;,
  0.742573; 0.812627;,
  0.748381; 0.812627;,
  0.754226; 0.812627;,
  0.760131; 0.812627;,
  0.766089; 0.812627;,
  0.772069; 0.812627;,
  0.778027; 0.812627;,
  0.783932; 0.812627;,
  0.789778; 0.812627;,
  0.769079; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.995429;,
  0.713077; 0.812627;,
  0.713077; 0.995429;,
  0.713077; 0.812627;;
  }		// End MeshTexture Coords for 'Barrel1'
}		// End of Mesh 'Barrel1'

AnimLinkName { //Barrel1 
    "Barrel1";
}
}		 // End of frame frm-Barrel1

}		 // End of RotateAroundX frame

}		 // End of frm-MasterUnitConversion frame

}		 // End of frm-MasterScale frame

